name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
    
    - name: Login to ECR
      run: aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 027598210508.dkr.ecr.ap-south-1.amazonaws.com
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag 027598210508.dkr.ecr.ap-south-1.amazonaws.com/my-todo-app:$(date +%s) --tag 027598210508.dkr.ecr.ap-south-1.amazonaws.com/my-todo-app:latest
    
    - name: Push to ECR
      run: docker push 027598210508.dkr.ecr.ap-south-1.amazonaws.com/my-todo-app --all-tags
    
    - name: Update ECS Fargate service
      if: github.event_name == 'push'
      run: |
        aws ecs update-service \
          --cluster my-cluster \
          --service my-service \
          --force-new-deployment \
          --region ap-south-1
